manager script updated

diff --git a/manager b/manager
--- a/manager
+++ b/manager
@@ -30,13 +30,13 @@ echo "   | # CONTAINER MENU #                                                 |"
 echo "   | -------------------------------------------------------------------|"
 echo "   | 1. Create Container  | 11. Container List   | 20. Manage Container |"
 echo "   | 2. Delete Container  | 12. Start Container  |                      |"
-echo "   |                      | 13. Reboot Container |                      |"
-echo "   |                      | 14. Stop Container   |                      |"
+echo "   |                      | 13. Stop Container   |                      |"
 echo "   |--------------------------------------------------------------------|"
 echo "   | # HOST MENU #                                                      |"
 echo "   |--------------------------------------------------------------------|"
-echo "   | 30. Set static ip    | 40. Add Storage                             |"
-echo "   | 31. Show ip          | 41. Mount List                              |"
+echo "   | 30. Set static ip    | 40. Disk List                               |"
+echo "   | 31. Show ip          | 41. Add Storage                             |"
+echo "   |                      | 42. Mount List                              |"
 echo "   |--------------------------------------------------------------------|"
 echo "   | 99.Exit                                                            |"
 echo "   |--------------------------------------------------------------------|"
@@ -55,20 +55,156 @@ W+=($i "$line")
 done < <( cat /tmp/container_list.txt)
 IND=$(whiptail --title "Container List" --menu "Chose one" 24 50 17 "${W[@]}" 3>&2 2>&1 1>&3)
 CHOOSE_CONTAINER=$(sed -n $IND\p /tmp/container_list.txt)
-#pause
 }
 
 function container_list(){
+tput setaf 1
 echo ""
 echo ":: Container List ::"
 echo "-----------------------------------"
+tput sgr 0
+
 lxc-ls -f
 pause
 }
 
-function start_container(){
+function create_container(){
+tput setaf 1
+echo ""
+echo ":: Create Container ::"
+echo "-----------------------------------"
+tput sgr 0
+
+if [ -f /etc/network/interfaces.d/debianhostnw ]; then
+	CONTAINER_NAME=$(whiptail --title "Container Name" --inputbox "Please enter the Container Name" 10 60  3>&1 1>&2 2>&3)
+	CONTAINER_IP=$(whiptail --title "Container IP Address" --inputbox "Please enter the Container IP Address" 10 60  3>&1 1>&2 2>&3)
+	CONTAINER_NETMASK=$(whiptail --title "Container Netmask" --inputbox "Please enter the Container Netmask" 10 60  3>&1 1>&2 2>&3)
+	CONTAINER_GATEWAY=$(whiptail --title "Container Gateway" --inputbox "Please enter the Container Gateway" 10 60  3>&1 1>&2 2>&3)
+	CONTAINER_DNS=$(whiptail --title "Container DNS" --inputbox "Please enter the Container DNS" 10 60  3>&1 1>&2 2>&3)
+	
+	IPCHECK=INCORRECT
+	echo "$CONTAINER_IP" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && IPCHECK=CORRECT
+	rm /tmp/check_ip
+	
+	NETMASKCHECK=INCORRECT
+	echo "$CONTAINER_NETMASK" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && NETMASKCHECK=CORRECT
+	
+	GWCHECK=INCORRECT
+	echo "$CONTAINER_GATEWAY" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && GWCHECK=CORRECT
+	
+	DNSCHECK=INCORRECT
+	echo "$CONTAINER_DNS" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && DNSCHECK=CORRECT
+
+	if [ $IPCHECK = CORRECT ] && [ $NETMASKCHECK = CORRECT ] && [ $GWCHECK = CORRECT ] && [ $DNSCHECK = CORRECT ]; then
+		lxc-copy -n template-container -N $CONTAINER_NAME -p /var/lib/lxc/
+		cat > /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/network/interfaces.d/debianhost_containernw << EOF
+		auto eth0
+		iface eth0 inet static
+		address $CONTAINER_IP
+		netmask $CONTAINER_NETMASK
+		gateway $CONTAINER_GATEWAY
+EOF
+		chmod 644 /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/network/interfaces.d/debianhost_containernw
+		sed -i /eth0/d /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/network/interfaces
+		echo "nameserver $CONTAINER_DNS" > /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/resolv.conf
+
+		cat > /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/apt/sources.list << EOF
+		deb http://deb.debian.org/debian buster main non-free contrib
+		deb-src http://deb.debian.org/debian buster main non-free contrib
+		deb http://deb.debian.org/debian buster-updates main non-free contrib
+		deb-src http://deb.debian.org/debian buster-updates main non-free contrib
+		deb http://security.debian.org/ buster/updates main contrib non-free
+		deb-src http://security.debian.org/ buster/updates main contrib non-free
+EOF
+
+		CHOICE=$(whiptail --title "select the service to install" --radiolist "Choose:" 15 40 6 \
+		"install nextcloud server" "" "nextcloud-server" \
+		"install ansible server" "" "ansible-server" 3>&1 1>&2 2>&3)
+		case $CHOICE in  
+		"install nextcloud server")
+			mkdir -p /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost
+			cp /usr/local/debianhost/installer/nextcloud-server-install.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/
+			cp /usr/local/debianhost/installer/nextcloud-server-manager.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/manager
+			lxc-start -n $CONTAINER_NAME -d
+			lxc-wait -n $CONTAINER_NAME -s RUNNING && sleep 3
+			lxc-attach -n $CONTAINER_NAME -- bash -c "set -e && echo $CONTAINER_NAME > /etc/hostname && sed -i 's/\(127.0.1.1\s*\).*$/\1$CONTAINER_NAME/' /etc/hosts && hostname $CONTAINER_NAME"
+			lxc-attach -n $CONTAINER_NAME -- bash -c "apt-get update && apt-get -y full-upgrade"
+			lxc-attach -n $CONTAINER_NAME -- bash -c "bash /usr/local/debianhost/nextcloud-server-install.sh"
+		;;
+		"install ansible server")
+			mkdir -p /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost
+			cp /usr/local/debianhost/installer/ansible-server-install.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/
+			cp /usr/local/debianhost/installer/ansible-server-manager.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/manager
+			lxc-start -n $CONTAINER_NAME -d
+			lxc-wait -n $CONTAINER_NAME -s RUNNING && sleep 3
+			lxc-attach -n $CONTAINER_NAME -- bash -c "set -e && echo $CONTAINER_NAME > /etc/hostname && sed -i 's/\(127.0.1.1\s*\).*$/\1$CONTAINER_NAME/' /etc/hosts && hostname $CONTAINER_NAME"
+			lxc-attach -n $MACH -- bash -c "set -e && export DEBIAN_FRONTEND=noninteractive && apt-get -dy reinstall hostname"
+			lxc-attach -n $CONTAINER_NAME -- bash -c "apt-get update && apt-get -y full-upgrade"
+			lxc-attach -n $CONTAINER_NAME -- bash -c "bash /usr/local/debianhost/ansible-server-install.sh"
+		;;
+		*)
+		;;
+		esac
+	else
+		MSG="Please enter addresses in the suitable format"
+		whiptail --title "Container Creator" --msgbox "$MSG" 10 60  3>&1 1>&2 2>&3
+	fi
+
+else
+	MSG="DebianHost machine, static thread is not set.\nYou must first set the static ip from the menu number 30"
+	whiptail --title "Container Creator" --msgbox "$MSG" 10 60  3>&1 1>&2 2>&3
+fi	
+pause
+}
+
+function delete_container(){
+tput setaf 1
+echo ""
+echo ":: Delete Container ::"
+echo "----------------------------"
+tput sgr 0
+
 list_container
-	lxc-start -n $CHOOSE_CONTAINER
+
+if (whiptail --title "Remove Container.." --yesno "Do you want to remove the $CHOOSE_CONTAINER container and container disk if exist?" 8 85 --no-button "No" --yes-button "Yes"); then
+	lxc-stop -n $CHOOSE_CONTAINER
+	lxc-destroy -n $CHOOSE_CONTAINER
+	if [ -d /media/$CHOOSE_CONTAINER ]; then
+		umount /media/$CHOOSE_CONTAINER
+		rm -r /media/$CHOOSE_CONTAINER
+		sed -i /$CHOOSE_CONTAINER/d /etc/fstab
+		sed -i '/^$/d' /etc/fstab
+	fi
+else
+	echo "remove process canceled"
+fi
+
+pause
+}
+
+function start_container(){
+tput setaf 1
+echo ""
+echo ":: Start Container ::"
+echo "----------------------------"
+tput sgr 0
+
+list_container
+lxc-start -n $CHOOSE_CONTAINER
+
+pause
+}
+
+function stop_container(){
+tput setaf 1
+echo ""
+echo ":: Stop Container ::"
+echo "----------------------------"
+tput sgr 0
+
+list_container
+lxc-stop -n $CHOOSE_CONTAINER
+
 pause
 }
 
@@ -76,90 +212,6 @@ function manage_container(){
 list_container
 	lxc-attach -n $CHOOSE_CONTAINER -- bash -c "bash /usr/local/debianhost/manager"
 
-pause
-}
-
-function create_container(){
-echo ""
-echo ":: Create Container ::"
-echo "-----------------------------------"
-CONTAINER_NAME=$(whiptail --title "Container Name" --inputbox "Please enter the Container Name" 10 60  3>&1 1>&2 2>&3)
-CONTAINER_IP=$(whiptail --title "Container IP Address" --inputbox "Please enter the Container IP Address" 10 60  3>&1 1>&2 2>&3)
-CONTAINER_NETMASK=$(whiptail --title "Container Netmask" --inputbox "Please enter the Container Netmask" 10 60  3>&1 1>&2 2>&3)
-CONTAINER_GATEWAY=$(whiptail --title "Container Gateway" --inputbox "Please enter the Container Gateway" 10 60  3>&1 1>&2 2>&3)
-CONTAINER_DNS=$(whiptail --title "Container DNS" --inputbox "Please enter the Container DNS" 10 60  3>&1 1>&2 2>&3)
-
-IPCHECK=INCORRECT
-echo "$CONTAINER_IP" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && IPCHECK=CORRECT
-rm /tmp/check_ip
-
-NETMASKCHECK=INCORRECT
-echo "$CONTAINER_NETMASK" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && NETMASKCHECK=CORRECT
-
-GWCHECK=INCORRECT
-echo "$CONTAINER_GATEWAY" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && GWCHECK=CORRECT
-
-DNSCHECK=INCORRECT
-echo "$CONTAINER_DNS" |egrep $REGEX |tee /tmp/check_ip > /dev/null && ack "." /tmp/check_ip > /dev/null && DNSCHECK=CORRECT
-
-if [ $IPCHECK = CORRECT ] && [ $NETMASKCHECK = CORRECT ] && [ $GWCHECK = CORRECT ] && [ $DNSCHECK = CORRECT ]; then
-lxc-copy -n template-container -N $CONTAINER_NAME -p /var/lib/lxc/
-
-cat > /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/network/interfaces.d/debianhost_containernw << EOF
-auto eth0
-iface eth0 inet static
-address $CONTAINER_IP
-netmask $CONTAINER_NETMASK
-gateway $CONTAINER_GATEWAY
-EOF
-chmod 644 /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/network/interfaces.d/debianhost_containernw
-sed -i /eth0/d /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/network/interfaces
-echo "nameserver $CONTAINER_DNS" > /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/resolv.conf
-
-cat > /var/lib/lxc/$CONTAINER_NAME/rootfs/etc/apt/sources.list << EOF
-deb http://deb.debian.org/debian buster main non-free contrib
-deb-src http://deb.debian.org/debian buster main non-free contrib
-deb http://deb.debian.org/debian buster-updates main non-free contrib
-deb-src http://deb.debian.org/debian buster-updates main non-free contrib
-deb http://security.debian.org/ buster/updates main contrib non-free
-deb-src http://security.debian.org/ buster/updates main contrib non-free
-EOF
-
-CHOICE=$(whiptail --title "select the service to install" --radiolist "Choose:" 15 40 6 \
-"install nextcloud server" "" "nextcloud-server" \
-"install ansible server" "" "ansible-server" 3>&1 1>&2 2>&3)
-case $CHOICE in
-"install nextcloud server")
-	mkdir -p /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost
-	cp /usr/local/debianhost/installer/nextcloud-server-install.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/
-	cp /usr/local/debianhost/installer/nextcloud-server-manager.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/manager
-
-	lxc-start -n $CONTAINER_NAME -d
-	lxc-wait -n $CONTAINER_NAME -s RUNNING && sleep 3
-	lxc-attach -n $CONTAINER_NAME -- bash -c "set -e && echo $CONTAINER_NAME > /etc/hostname && sed -i 's/\(127.0.1.1\s*\).*$/\1$CONTAINER_NAME/' /etc/hosts && hostname $CONTAINER_NAME"
-	lxc-attach -n $CONTAINER_NAME -- bash -c "apt-get update && apt-get -y full-upgrade"
-	lxc-attach -n $CONTAINER_NAME -- bash -c "bash /usr/local/debianhost/nextcloud-server-install.sh"
-;;
-"install ansible server")
-	mkdir -p /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost
-	cp /usr/local/debianhost/installer/ansible-server-install.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/
-	cp /usr/local/debianhost/installer/ansible-server-manager.sh /var/lib/lxc/$CONTAINER_NAME/rootfs/usr/local/debianhost/manager
-
-	lxc-start -n $CONTAINER_NAME -d
-	lxc-wait -n $CONTAINER_NAME -s RUNNING && sleep 3
-	lxc-attach -n $CONTAINER_NAME -- bash -c "set -e && echo $CONTAINER_NAME > /etc/hostname && sed -i 's/\(127.0.1.1\s*\).*$/\1$CONTAINER_NAME/' /etc/hosts && hostname $CONTAINER_NAME"
-	lxc-attach -n $MACH -- bash -c "set -e && export DEBIAN_FRONTEND=noninteractive && apt-get -dy reinstall hostname"
-	lxc-attach -n $CONTAINER_NAME -- bash -c "apt-get update && apt-get -y full-upgrade"
-	lxc-attach -n $CONTAINER_NAME -- bash -c "bash /usr/local/debianhost/ansible-server-install.sh"
-;;
-*)
-;;
-esac
-
-else
-	whiptail --title "Container Creator" --msgbox "Please enter addresses in the suitable format" 10 60  3>&1 1>&2 2>&3
-
-fi
 pause
 }
 
@@ -226,6 +278,17 @@ fi
 pause
 }
 
+function disk_list(){
+tput setaf 1
+echo ""
+echo ":: Disk List ::"
+echo "----------------------------"
+tput sgr 0
+	
+fdisk -l |grep /dev/
+pause
+}
+
 function add_storage(){
 CHOICE=$(whiptail --title "select the source" --radiolist "Choose:" 15 40 6 \
 	"Add Disk" "" "add-disk" 3>&1 1>&2 2>&3)
@@ -235,7 +298,7 @@ case $CHOICE in
 		if [ ! -z "$CHOICE" ]; then
 			if [ ! -d /media/$CHOOSE_CONTAINER ]; then
 				mkdir /media/$CHOOSE_CONTAINER
-				fdisk -l |grep "Disk /dev" | cut -d ":" -f1 |cut -d " " -f2 > /tmp/disk_list.txt
+				fdisk -l |grep "Disk /dev" |grep -v "sda" |cut -d ":" -f1 |cut -d " " -f2 > /tmp/disk_list.txt
 				let i=0
 				W=()
 				
@@ -259,7 +322,8 @@ case $CHOICE in
 					PARTITION=$(fdisk -l $CHOOSE_DISK |grep "$CHOOSE_DISK"1 |cut -d " " -f1)
 					mkfs.ext4 $PARTITION
 					sleep 1
-					mount $PARTITION /media/$CHOOSE_CONTAINER
+					echo "$PARTITION    /media/$CHOOSE_CONTAINER    ext4    defaults,nofail 0 0 #for $CHOOSE_CONTAINER" >> /etc/fstab
+					mount -a
 					rm /tmp/disk_list.txt
 				else
 					whiptail --title "Add Disk Error" --msgbox "$CHOOSE_DISK already used" 10 60  3>&1 1>&2 2>&3
@@ -276,24 +340,37 @@ pause
 }
 
 function mount_list(){
+tput setaf 1
+echo ""
+echo ":: Mount List ::"
+echo "----------------------------"
+tput sgr 0
+
 mount |grep /media/
 pause
 }
 
 function read_input(){
+tput setaf 6
 local c
 read -p "You can choose from the menu numbers " c
+tput sgr0
 case $c in
 1)	create_container ;;
+2)	delete_container ;;
 11)	container_list ;;
 12)	start_container ;;
+13)	stop_container ;;
 20)	manage_container ;;
 30)	set_static_ip ;;
-40)	add_storage ;;
-41)	mount_list ;;
+40)	disk_list ;;
+41)	add_storage ;;
+42)	mount_list ;;
 99)	exit 0 ;;
 *)	
+tput setaf 1
 echo "Please select from the menu numbers"
+tput sgr0
 pause
 esac
 }
